# Generated by Django 2.0.3 on 2018-06-16 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                (
                    'comment',
                    models.CharField(max_length=300, verbose_name='评论')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='votedown_nums',
            field=models.IntegerField(default=0, verbose_name='不认同数'),
        ),
        migrations.AddField(
            model_name='answer',
            name='voteup_nums',
            field=models.IntegerField(default=0, verbose_name='认同数'),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='zhihu.Answer', verbose_name='回答'),
        ),
        migrations.AddField(
            model_name='answercomment',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
