# Generated by Django 2.0.3 on 2018-06-16 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zhihu', '0002_auto_20180616_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('follow_type',
                 models.IntegerField(blank=True, choices=[(1, '点赞'), (2, '收藏')],
                                     null=True)),
                ('add_time',
                 models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('answer', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='zhihu.Answer', verbose_name='回答')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('add_time',
                 models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='read_nums',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
        migrations.AddField(
            model_name='userfollowquestion',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='zhihu.Question', verbose_name='问题'),
        ),
        migrations.AddField(
            model_name='userfollowquestion',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
