# Generated by Django 2.0.3 on 2018-06-22 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zhihu', '0005_auto_20180622_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('add_time',
                 models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('answer', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to='zhihu.Answer', verbose_name='回答')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.RemoveField(
            model_name='userfollowanswer',
            name='follow_type',
        ),
    ]
