# Generated by Django 2.0.3 on 2018-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zhihu', '0007_auto_20180625_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='匿名问题'),
        ),
    ]
