# Generated by Django 2.0.3 on 2018-06-26 15:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('zhihu', '0009_answer_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name='回答内容'),
        ),
    ]
