# Generated by Django 2.0.3 on 2018-06-29 12:30

from django.conf import settings
from django.db import migrations, models
import zhihu.models


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0011_auto_20180629_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(zhihu.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='回答作者'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=models.SET(zhihu.models.get_sentinel_question), to='zhihu.Question', verbose_name='回答问题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=models.SET(zhihu.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='问题作者'),
        ),
    ]
