# Generated by Django 2.0.3 on 2018-06-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_user_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('check_code',
                 models.CharField(max_length=8, verbose_name='验证码')),
                ('add_time',
                 models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='用户')),
            ],
        ),
    ]
