# Generated by Django 2.0.3 on 2018-06-28 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180627_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_set', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user_set', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(through='user.UserRelationship', to=settings.AUTH_USER_MODEL, verbose_name='关注者'),
        ),
    ]
