# Generated by Django 2.0.3 on 2018-06-28 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_auto_20180628_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_time',
        ),
    ]
