# Generated by Django 2.0.3 on 2018-06-28 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_remove_user_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(through='user.UserRelationship',
                                         to=settings.AUTH_USER_MODEL,
                                         verbose_name='关注'),
        ),
        migrations.AlterField(
            model_name='userrelationship',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='from_user_set',
                                    to=settings.AUTH_USER_MODEL,
                                    verbose_name='关注'),
        ),
    ]
